GET http://localhost:3001/todos 

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Order milk"
}

###

DELETE http://localhost:3001/todo/delete/6455ece279a0af3285e410ca


###

PUT http://localhost:3001/todo/complete/6455c4146a5d115d2ca18b7d
